# Generated by Django 4.0.3 on 2022-05-14 18:00

import django.core.validators
from django.db import migrations, models
import petstagram.main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_petphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), petstagram.main.validators.validate_only_letters], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), petstagram.main.validators.validate_only_letters], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.URLField(verbose_name='Link to Profile Picture'),
        ),
    ]
